name: peh
version: 0.0.1

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - containers
  - errors
  - hslua
  - megaparsec
  - network-simple
  - pipes
  - pipes-break
  - pipes-extras
  - pipes-bytestring
  - pipes-concurrency
  - pipes-network
  - pipes-safe
  - pipes-text
  - random
  - Spock
  - sqlite-simple
  - text

default-extensions:
  - FlexibleContexts
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

executables:
  datagen:
    source-dirs: datagen
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

  datacon:
    source-dirs: datacon
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
