name: peh
version: 0.0.1

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - io-streams
  - network-fancy
  - random
  - text

default-extensions:
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

executables:
  datagen:
    source-dirs: datagen
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

  datacon:
    source-dirs: datacon
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
